#! /usr/bin/python3
# -*- coding: utf-8 -*-

import sys
import subprocess
try:
    import tkinter as tk
except ImportError:
    import Tkinter as tk

ALSAUCM = "/usr/bin/alsaucm"

class AudioSelectFrame(tk.Frame):
    BOARD = "cht-bsw-rt5672"
    #BOARD = "cherrytrailcraudio"
    VERB = "HiFi"
    
    OUTPUT = ("Speaker", "Headphones")
    INPUT = ("DigitalMics", "HeadsetMic")

    def __init__(self, parent=None):
        tk.Frame.__init__(self, parent)

        frm_select = tk.Frame(self)
        self.out_var = self._make_optmenu(
            frm_select, "出力先: ", self.OUTPUT)
        self.in_var = self._make_optmenu(
            frm_select, "入力元: ", self.INPUT)
        frm_select.pack()

        frm_button = tk.Frame(self)
        btn_ok = tk.Button(
            frm_button, text="Apply", command=self.cmd_apply)
        btn_cancel = tk.Button(
            frm_button, text="Quit", command=self.cmd_quit)
        btn_ok.pack(side=tk.LEFT, padx=2, pady=2)
        btn_cancel.pack(side=tk.LEFT, padx=2, pady=2)
        frm_button.pack(padx=5, pady=5)
        
        self.pack()
        
    def _make_optmenu(self, parent, label, options):
        frm = tk.Frame(parent)
        lbl = tk.Label(frm, text=label)
        var = tk.StringVar()
        var.set(options[0])
        om = tk.OptionMenu(frm, var, *options)
        lbl.pack(side=tk.LEFT, anchor=tk.W)
        om.pack(side=tk.LEFT, anchor=tk.W)
        frm.pack(side=tk.TOP, anchor=tk.W, fill=tk.BOTH, padx=2, pady=2)
        return var

    def cmd_apply(self):
        subprocess.call([
            ALSAUCM, '-c', self.BOARD, 'set', '_verb', self.VERB,
            'set', '_enadev', self.out_var.get(),
            'set', '_enadev', self.in_var.get()
        ])
        
    def cmd_quit(self):
        sys.exit(1)


def geo_center(root, size):
    w = root.winfo_screenwidth()
    h = root.winfo_screenheight()
    x = int((w - size[0])/2)
    y = int((h - size[1])/2)
    root.geometry("{}x{}+{}+{}".format(size[0], size[1], x, y))
    
def main():
    root = tk.Tk()
    root.title("入出力変更")
    frame = AudioSelectFrame()
    geo_center(root, (200, 100))
    root.resizable(False, False)
    root.mainloop()

if __name__ == "__main__":
    main()
